<?php

namespace AppBundle\Entity\Repository;

/**
 * ExtraFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraFieldsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getExtraFieldList(){
        $q = $this->createQueryBuilder('e')
                ->orderBy('e.title', 'ASC')
        ->getQuery();
        return $q;
    }

	public function deleteCategoryExtraFieldsLinks($id){
		$query = "DELETE FROM `category_fields` WHERE `extra_fields_id` =  :id;";
		$params = array(
		    'id' => $id,
		);
		return $this->getEntityManager()->getConnection()->executeQuery($query, $params);
    }

	public function deleteGoodExtraFieldsLinks($id){
		$query = "DELETE FROM `good_extra_field` WHERE `extra_field_id` =  :id;";
		$params = array(
		    'id' => $id,
		);
		return $this->getEntityManager()->getConnection()->executeQuery($query, $params);
    }
}
